import type { EventCmsBundle } from '../admin/types/contentSchema'

export const EMPTY_CONTENT: EventCmsBundle = {
  site: {
    siteName: 'K-SENSUAL',
    tagline: '',
    description: '',
    contactEmail: '',
    instagramUrl: '',
    whatsappUrl: '',
    primaryCtaLabel: 'Explore',
    primaryCtaLink: '/',
    updatedAt: new Date().toISOString(),
  },
  eventInfo: {
    name: 'K-SENSUAL',
    slogan: '',
    description: '',
    startDate: '',
    endDate: '',
    venueName: '',
    address: '',
    googleMapLink: '',
    ticketLink: '',
    posterImage: '',
    primaryCtaText: 'Get Tickets',
  },
  hero: {
    title: 'K-SENSUAL',
    subtitle: '',
    description: '',
    backgroundType: 'image',
    backgroundUrl: '',
    backgroundMobileUrl: '',
    ctaLabel: 'Lineup',
    ctaLink: '/lineup',
  },
  artists: [],
  workshops: [],
  parties: [],
  schedule: [],
  gallery: [],
  faq: [],
  notices: [],
}
